name: Deploy

on:
  pull_request:
    - develop
    - staging
    - master
  push:
    - develop
    - staging
    - master  

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy my app
        run: |
          echo "Deploying my APP........."
