name: Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "develop"
      - "staging"
      - "master"
  push:
    branches:
      - "develop"
      - "staging"
      - "master"      


jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Deploy my app
        run: |
          echo "Deploying my APP........."
