name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "develop"
      - "staging"
      - "master"          

 

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v4

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          environment-url: http://my-app-url.com
          environment: ${{github.ref_name}}

      - name: Deploy my app
        run: |
          echo "Deploying my app"

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'